spring:
  datasource:
    url: jdbc:mysql://localhost:3306/examplesdb?useSSL=false&serverTimezone=Asia/Seoul
    username: ustory
    password: r1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql   # ??
    database-platform: org.hibernate.dialect.MySQL8Dialect # ??

    hibernate:
      ddl-auto: create  # ??? ?? ??
    show-sql: true      # SQL ?? ??